version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./filestore:/app/filestore
    depends_on:
      - db
      - redis
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: base
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
  redis:
    image: redis
    volumes:
      - ./dbdata/redis:/data

volumes:
    dbdata: