services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 3000
        env_file:
            - ".env"
        volumes:
            - "./filestore:/app/filestore:rw"
        labels:
            - traefik.enable=true
            - traefik.http.routers.web.rule=Host(`${DOKPLOY_DOMAIN}`)
            - traefik.http.routers.web.entrypoints=web
            - traefik.http.services.web.loadbalancer.server.port=3000

networks:
    default:
        name: dokploy-network
        external: true
