version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data      
      - ./db/schema.sql:/var/lib/postgresql/data/schema.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    command: psql -U $POSTGRES_USER -d $POSTGRES_DB -a -f /var/lib/postgresql/data/schema.sql
  
  redis:
    image: redis
    ports:
      - "6379:6379"