services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 3000
        env_file:
            - ".env"
        volumes:
            - "./filestore:/app/filestore:rw"        

networks:
    default:
        name: dokploy-network
        external: true
