allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  sharp: true
  vue-demi: false

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - vue-demi

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - sharp
